"""update question  model

Revision ID: 0ad896b1af3f
Revises: 628f904342a2
Create Date: 2023-12-26 01:12:33.918365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ad896b1af3f'
down_revision: Union[str, None] = '628f904342a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Question', 'scores')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Question', sa.Column('scores', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
