"""update exercise model

Revision ID: 628f904342a2
Revises: 7c958e8a2e97
Create Date: 2023-12-25 22:13:14.874815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '628f904342a2'
down_revision: Union[str, None] = '7c958e8a2e97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Exercise', sa.Column('theory', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Exercise', 'theory')
    # ### end Alembic commands ###
