"""create database

Revision ID: 7c958e8a2e97
Revises: 
Create Date: 2023-12-25 22:11:38.346218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c958e8a2e97'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Exercise',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('theme', sa.Enum('MATH', 'ENGLISH', 'NATURE', name='exercisetopic'), nullable=False),
    sa.Column('level', sa.Enum('EASY', 'MEDIUM', 'HARD', name='exerciselevel'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Student',
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Teacher',
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Question',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question_text', sa.String(), nullable=False),
    sa.Column('scores', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['Exercise.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Answer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['Question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Answer')
    op.drop_table('Question')
    op.drop_table('Teacher')
    op.drop_table('Student')
    op.drop_table('Exercise')
    # ### end Alembic commands ###
